export const USER_LOGIN_ACTION = "USER_LOGIN_ACTION";
export const USER_LOGIN_RESPONSE_ACTION = "USER_LOGIN_RESPONSE_ACTION";

export const JOIN_ROOM_ACTION = "JOIN_ROOM_ACTION";
export const JOIN_ROOM_RESPONSE_ACTION = "JOIN_ROOM_RESPONSE_ACTION";

// WebSocket Actions
export const WEBSOCKET_INITIALIZED_ACTION = "WEBSOCKET_INITIALIZED_ACTION"; 
export const WEBSOCKET_OPEN_ACTION = "WEBSOCKET_OPEN_ACTION";