export const LOGIN_ACTION = "LOGIN_ACTION";
export const SIGNALR_CONNECT_ACTION = "SIGNALR_CONNECT_ACTION";
export const SEND_CHAT_MESSAGE_ACTION = "SEND_CHAT_MESSAGE_ACTION";
export const RECEIVE_CHAT_MESSAGE_ACTION = "RECEIVE_CHAT_MESSAGE_ACTION";
