export const SIGNALR_CONNECT_ACTION = "SIGNALR_CONNECT_ACTION";

export const GAME_REQUEST_ACCESS_ACTION = "GAME_REQUEST_ACCESS_ACTION";
export const GAME_ACCESS_RESPONSE_ACTION = "GAME_ACCESS_RESPONSE_ACTION";

export const SEND_CHAT_MESSAGE_ACTION = "SEND_CHAT_MESSAGE_ACTION";
export const RECEIVE_CHAT_MESSAGE_ACTION = "RECEIVE_CHAT_MESSAGE_ACTION";

export const ROUND_STARTED_ACTION = "ROUND_STARTED_ACTION";
export const SUBMIT_CAPTION_ACTION = "SUBMIT_CAPTION_ACTION";