const GameState = {
  DEFAULT: "DEFAULT",
  GAME_STARTING: "GAME_STARTING",
  ROUND_STARTING: "ROUND_STARTING",
  SUBMISSION_CLOSED: "SUBMISSION_CLOSED",
  ROUND_FINISHED: "ROUND_FINISHED"
};

export default GameState;